// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fylblmrickfhedpmvlny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5bGJsbXJpY2tmaGVkcG12bG55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NjIyODQsImV4cCI6MjA2NjIzODI4NH0.qLFHv1976xarZ3b6iZtSELJvaeR7JfXLvPwMirq6qTE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);